Name:           ros-indigo-explorer
Version:        0.1.8
Release:        0%{?dist}
Summary:        ROS explorer package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/explorer
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-adhoc-communication
Requires:       ros-indigo-costmap-2d
Requires:       ros-indigo-map-merger
Requires:       ros-indigo-message-runtime
Requires:       ros-indigo-move-base
Requires:       ros-indigo-nav-core
Requires:       ros-indigo-navfn
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-rospy
Requires:       ros-indigo-sound-play
Requires:       ros-indigo-std-msgs
Requires:       ros-indigo-voxel-grid
BuildRequires:  ros-indigo-adhoc-communication
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-costmap-2d
BuildRequires:  ros-indigo-map-merger
BuildRequires:  ros-indigo-message-generation
BuildRequires:  ros-indigo-move-base
BuildRequires:  ros-indigo-nav-core
BuildRequires:  ros-indigo-navfn
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-rospy
BuildRequires:  ros-indigo-sound-play
BuildRequires:  ros-indigo-std-msgs
BuildRequires:  ros-indigo-voxel-grid

%description
The explorer package utilizes frontier based exploration for multi-robot
systems. Beside frontier detection, coordinated and uncoordinated exploration
strategies are available to select goal points. Coordinated exploration enhances
robot distribution and reduces redundancy in exploration reducing exploration
time.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Jul 03 2015 Daniel Neuhold <dneuhold@edu.aau.at> - 0.1.8-0
- Autogenerated by Bloom

